package contractstudy.evolution.constants;

public enum DiffResult {
  UNCHANGED,
  MINOR_CHANGE,
  POSTCONDITION_ADDED,
  POSTCONDITION_REMOVED,
  PRECONDITION_ADDED,
  PRECONDITION_REMOVED,
  OTHER_INCOMPATBIBLE_CHANGE,
  CANNOT_BE_CLASSIFIED
}
