package contractstudy;

import java.util.function.Function;

import static contractstudy.ConstraintClassifiers._POSTCONDITION;
import static contractstudy.ConstraintClassifiers._PRECONDITION;
import static contractstudy.ConstraintClassifiers._STANDARD_ANNOTATION;
import static contractstudy.ConstraintClassifiers._UNKNOWN;

/**
 * Represents types of constraints found in Java classes. constraint type > contstraint group >
 * constraint category example: ConstraintTypeJSR303Null > ConstraintGroup.ANNO_JSR30 >
 * ConstraintCategory.ANNOTATION
 *
 * @author jens dietrich
 */
public enum ConstraintType {

  CREActivityNotFoundException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CREAndroidRuntimeException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CREAnnotationTypeMismatchException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CREArithmeticException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION, TVL.MAYBE),
  CREArrayStoreException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION, TVL.MAYBE),
  CREBufferOverflowException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CREBufferUnderflowException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CREClassCastException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION, TVL.MAYBE),
  CRECompletionException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION, TVL.MAYBE),
  CREConcurrentModificationException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CREDOMException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION, TVL.MAYBE),
  CREDateTimeException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION, TVL.MAYBE),
  CREEmptyStackException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION, TVL.MAYBE),
  CREEnumConstantNotPresentException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CREFileSystemAlreadyExistsException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CREFileSystemNotFoundException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CREFileUriExposedException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CREGLException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION, TVL.MAYBE),
  CREICUUncheckedIOException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CREIllegalArgumentException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CREIllegalMonitorStateException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CREIllegalStateException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION, TVL.MAYBE),
  CREIllformedLocaleException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CREIncompleteAnnotationException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CREIndexOutOfBoundsException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CREInflateException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION, TVL.MAYBE),
  // CREInspectionCompanion.UninitializedPropertyMapException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION,
  // _PRECONDITION, TVL.MAYBE),
  CREUninitializedPropertyMapException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CRELSException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION, TVL.MAYBE),
  CREMalformedParameterizedTypeException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION,
    _PRECONDITION, TVL.MAYBE),
  CREMalformedParametersException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  // CREMediaCodec.CryptoException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION,
  // _PRECONDITION, TVL.MAYBE),
  CRECryptoException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION, TVL.MAYBE),
  // CREMediaCodec.IncompatibleWithBlockModelException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION,
  // _PRECONDITION, TVL.MAYBE),
  CREIncompatibleWithBlockModelException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION,
    _PRECONDITION, TVL.MAYBE),
  // CREMediaDrm.SessionException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION,
  // _PRECONDITION, TVL.MAYBE),
  CRESessionException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION, TVL.MAYBE),
  CREMissingResourceException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CRENegativeArraySizeException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CRENetworkOnMainThreadException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CRENoSuchElementException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CRENoSuchPropertyException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CRENullPointerException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION, TVL.MAYBE),
  CREOperationCanceledException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CREParcelFormatException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION, TVL.MAYBE),
  CREParseException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION, TVL.MAYBE),
  // CREPropertyMapper.PropertyConflictException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION,
  // _PRECONDITION, TVL.MAYBE),
  CREPropertyConflictException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  // CREPropertyReader.PropertyTypeMismatchException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION,
  // _PRECONDITION, TVL.MAYBE),
  CREPropertyTypeMismatchException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CREProviderException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION, TVL.MAYBE),
  CREProviderNotFoundException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CRERSRuntimeException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION, TVL.MAYBE),
  CRERejectedExecutionException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  // CRERemoteViews.ActionException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION,
  // _PRECONDITION, TVL.MAYBE),
  CREActionException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION, TVL.MAYBE),
  // CREResources.NotFoundException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION,
  // _PRECONDITION, TVL.MAYBE),
  CRENotFoundException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION, TVL.MAYBE),
  CRESQLException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION, TVL.MAYBE),
  CRESecurityException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION, TVL.MAYBE),
  CREStaleDataException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION, TVL.MAYBE),
  // CRESurface.OutOfResourcesException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION,
  // _PRECONDITION, TVL.MAYBE),
  CREOutOfResourcesException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  // CRESurfaceHolder.BadSurfaceTypeException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION,
  // _PRECONDITION, TVL.MAYBE),
  CREBadSurfaceTypeException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CRETimeFormatException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION, TVL.MAYBE),
  CRETypeNotPresentException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CREUncheckedIOException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION, TVL.MAYBE),
  CREUndeclaredThrowableException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CREUnsupportedOperationException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  // CREUserManager.UserOperationException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION,
  // _PRECONDITION, TVL.MAYBE),
  CREUserOperationException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  // CREWindowManager.BadTokenException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION,
  // _PRECONDITION, TVL.MAYBE),
  CREBadTokenException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION, TVL.MAYBE),
  // CREWindowManager.InvalidDisplayException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION,
  // _PRECONDITION, TVL.MAYBE),
  CREInvalidDisplayException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CREWrongMethodTypeException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CREAcceptPendingException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CREAccessControlException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CREAlreadyBoundException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION, TVL.MAYBE),
  CREAlreadyConnectedException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CREArrayIndexOutOfBoundsException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CREAuthenticationRequiredException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CREBadParcelableException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CRECancellationException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION, TVL.MAYBE),
  CRECancelledKeyException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION, TVL.MAYBE),
  CREClosedDirectoryStreamException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CREClosedFileSystemException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CREClosedSelectorException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CREClosedWatchServiceException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CREConnectionPendingException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CRECursorIndexOutOfBoundsException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CREDateTimeParseException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CREDirectoryIteratorException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CREDuplicateFormatFlagsException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CREFormatFlagsConversionMismatchException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION,
    _PRECONDITION, TVL.MAYBE),
  CREFormatterClosedException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  // CREFragment.InstantiationException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION,
  // _PRECONDITION, TVL.MAYBE),
  CREInstantiationException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CREIllegalBlockingModeException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CREIllegalChannelGroupException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CREIllegalCharsetNameException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CREIllegalFormatCodePointException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CREIllegalFormatConversionException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CREIllegalFormatException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CREIllegalFormatFlagsException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CREIllegalFormatPrecisionException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CREIllegalFormatWidthException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CREIllegalSelectorException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CREIllegalThreadStateException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CREInputMismatchException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CREInvalidMarkException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION, TVL.MAYBE),
  CREInvalidParameterException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CREInvalidPathException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION, TVL.MAYBE),
  // CREKeyCharacterMap.UnavailableException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION,
  // _PRECONDITION, TVL.MAYBE),
  CREUnavailableException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION, TVL.MAYBE),
  CRELimitExceededException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CREMediaCasStateException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  // CREMediaCodec.CodecException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION,
  // _PRECONDITION, TVL.MAYBE),
  CRECodecException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION, TVL.MAYBE),
  // CREMediaDrm.MediaDrmStateException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION,
  // _PRECONDITION, TVL.MAYBE),
  CREMediaDrmStateException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CREMediaDrmResetException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CREMissingFormatArgumentException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CREMissingFormatWidthException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CRENoConnectionPendingException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CRENonReadableChannelException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CRENonWritableChannelException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CRENotYetBoundException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION, TVL.MAYBE),
  CRENotYetConnectedException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CRENumberFormatException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION, TVL.MAYBE),
  CREOverlappingFileLockException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CREPatternSyntaxException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CREProviderMismatchException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CRERSDriverException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION, TVL.MAYBE),
  CRERSIllegalArgumentException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CRERSInvalidStateException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CREReadOnlyBufferException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CREReadOnlyFileSystemException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CREReadPendingException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION, TVL.MAYBE),
  CREReceiverCallNotAllowedException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CRERecoverableSecurityException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CRESQLiteAbortException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION, TVL.MAYBE),
  CRESQLiteAccessPermException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CRESQLiteBindOrColumnIndexOutOfRangeException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION,
    _PRECONDITION,
    TVL.MAYBE),
  CRESQLiteBlobTooBigException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CRESQLiteCantOpenDatabaseException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CRESQLiteConstraintException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CRESQLiteDatabaseCorruptException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CRESQLiteDatabaseLockedException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CRESQLiteDatatypeMismatchException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CRESQLiteDiskIOException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION, TVL.MAYBE),
  CRESQLiteDoneException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION, TVL.MAYBE),
  CRESQLiteException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION, TVL.MAYBE),
  CRESQLiteFullException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION, TVL.MAYBE),
  CRESQLiteMisuseException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION, TVL.MAYBE),
  CRESQLiteOutOfMemoryException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CRESQLiteReadOnlyDatabaseException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CRESQLiteTableLockedException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CRESecureKeyImportUnavailableException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION,
    _PRECONDITION, TVL.MAYBE),
  CREShutdownChannelGroupException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CREStringIndexOutOfBoundsException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CREStrongBoxUnavailableException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  // CRESystemUpdatePolicy.ValidationFailedException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION,
  // _PRECONDITION, TVL.MAYBE),
  CREValidationFailedException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CREUnknownFormatConversionException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CREUnknownFormatFlagsException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CREUnresolvedAddressException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CREUnsupportedAddressTypeException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CREUnsupportedCharsetException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CREUnsupportedTemporalTypeException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),
  CREWritePendingException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION, TVL.MAYBE),
  CREZoneRulesException(ConstraintGroup.CONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION, TVL.MAYBE),
  UCREUnsupportedOperationException(ConstraintGroup.UNCONDITIONAL_RUNTIME_EXCEPTION, _PRECONDITION,
    TVL.MAYBE),

  GuavaPreconditionCheckArgument(ConstraintGroup.CAPI_GUAVA, _PRECONDITION, TVL.MAYBE),
  GuavaPreconditionCheckState(ConstraintGroup.CAPI_GUAVA, _PRECONDITION, TVL.MAYBE),
  GuavaPreconditionElementIndex(ConstraintGroup.CAPI_GUAVA, _PRECONDITION, TVL.NO),
  GuavaPreconditionPositionIndex(ConstraintGroup.CAPI_GUAVA, _PRECONDITION, TVL.NO),
  GuavaPreconditionNotNull(ConstraintGroup.CAPI_GUAVA, _PRECONDITION, TVL.NO),
  GuavaPreconditionPositionIndexes(ConstraintGroup.CAPI_GUAVA, _PRECONDITION, TVL.MAYBE),

  // combine types for lang2 and lang3 APIs
  CommonsLangIsTrue(ConstraintGroup.CAPI_COMMONS_VALIDATE, _PRECONDITION, TVL.MAYBE),
  CommonsLangNoNullElements(ConstraintGroup.CAPI_COMMONS_VALIDATE, _PRECONDITION, TVL.YES),
  CommonsLangNotEmpty(ConstraintGroup.CAPI_COMMONS_VALIDATE, _PRECONDITION, TVL.NO),
  CommonsLangNotNull(ConstraintGroup.CAPI_COMMONS_VALIDATE, _PRECONDITION, TVL.NO),

  // commons lang2 only
  CommonsLang2AllElementsOfType(ConstraintGroup.CAPI_COMMONS_VALIDATE, _PRECONDITION, TVL.YES),

  // commons lang3 only
  CommonsLang3ExclusiveBetween(ConstraintGroup.CAPI_COMMONS_VALIDATE, _PRECONDITION, TVL.NO),
  CommonsLang3InclusiveBetween(ConstraintGroup.CAPI_COMMONS_VALIDATE, _PRECONDITION, TVL.NO),
  CommonsLang3IsAssignableFrom(ConstraintGroup.CAPI_COMMONS_VALIDATE, _PRECONDITION, TVL.NO),
  CommonsLang3IsInstanceOf(ConstraintGroup.CAPI_COMMONS_VALIDATE, _PRECONDITION, TVL.NO),
  CommonsLang3MatchesPattern(ConstraintGroup.CAPI_COMMONS_VALIDATE, _PRECONDITION, TVL.NO),
  CommonsLang3NotBlank(ConstraintGroup.CAPI_COMMONS_VALIDATE, _PRECONDITION, TVL.YES),
  CommonsLang3ValidIndex(ConstraintGroup.CAPI_COMMONS_VALIDATE, _PRECONDITION, TVL.NO),
  CommonsLang3ValidState(ConstraintGroup.CAPI_COMMONS_VALIDATE, _PRECONDITION, TVL.MAYBE),

  // spring assert
  SpringAssertDoesNotContain(ConstraintGroup.CAPI_SPRING_ASSERT, _PRECONDITION, TVL.NO),
  SpringAssertHasLength(ConstraintGroup.CAPI_SPRING_ASSERT, _PRECONDITION, TVL.NO),
  SpringAssertHasText(ConstraintGroup.CAPI_SPRING_ASSERT, _PRECONDITION, TVL.NO),
  SpringAssertNotEmpty(ConstraintGroup.CAPI_SPRING_ASSERT, _PRECONDITION, TVL.NO),
  SpringAssertNoNullElements(ConstraintGroup.CAPI_SPRING_ASSERT, _PRECONDITION, TVL.YES),
  SpringIsInstanceOf(ConstraintGroup.CAPI_SPRING_ASSERT, _PRECONDITION, TVL.NO),
  SpringIsAssignable(ConstraintGroup.CAPI_SPRING_ASSERT, _PRECONDITION, TVL.NO),
  SpringAssertState(ConstraintGroup.CAPI_SPRING_ASSERT, _PRECONDITION, TVL.MAYBE),
  SpringAssertIsNull(ConstraintGroup.CAPI_SPRING_ASSERT, _PRECONDITION, TVL.NO),
  SpringAssertIsTrue(ConstraintGroup.CAPI_SPRING_ASSERT, _PRECONDITION, TVL.MAYBE),
  SpringAssertNotNull(ConstraintGroup.CAPI_SPRING_ASSERT, _PRECONDITION, TVL.NO),

  JavaAssert(ConstraintGroup.ASSERTION, _UNKNOWN, TVL.MAYBE),

  // JSR303 annotations
  JSR303Null(ConstraintGroup.ANNO_JSR303, _STANDARD_ANNOTATION, TVL.NO),
  JSR303NotNull(ConstraintGroup.ANNO_JSR303, _STANDARD_ANNOTATION, TVL.NO),
  JSR303AssertTrue(ConstraintGroup.ANNO_JSR303, _STANDARD_ANNOTATION, TVL.NO),
  JSR303AssertFalse(ConstraintGroup.ANNO_JSR303, _STANDARD_ANNOTATION, TVL.NO),
  JSR303Min(ConstraintGroup.ANNO_JSR303, _STANDARD_ANNOTATION, TVL.NO),
  JSR303Max(ConstraintGroup.ANNO_JSR303, _STANDARD_ANNOTATION, TVL.NO),
  JSR303DecimalMin(ConstraintGroup.ANNO_JSR303, _STANDARD_ANNOTATION, TVL.NO),
  JSR303DecimalMax(ConstraintGroup.ANNO_JSR303, _STANDARD_ANNOTATION, TVL.NO),
  JSR303Size(ConstraintGroup.ANNO_JSR303, _STANDARD_ANNOTATION, TVL.NO),
  JSR303Digits(ConstraintGroup.ANNO_JSR303, _STANDARD_ANNOTATION, TVL.NO),
  JSR303Past(ConstraintGroup.ANNO_JSR303, _STANDARD_ANNOTATION, TVL.NO),
  JSR303Future(ConstraintGroup.ANNO_JSR303, _STANDARD_ANNOTATION, TVL.NO),
  JSR303Pattern(ConstraintGroup.ANNO_JSR303, _STANDARD_ANNOTATION, TVL.NO),

  // FindBugs annotations
  FindBugsCheckForNull(ConstraintGroup.ANNO_FINDBUGS, _STANDARD_ANNOTATION, TVL.NO),
  FindBugsNonNull(ConstraintGroup.ANNO_FINDBUGS, _STANDARD_ANNOTATION, TVL.NO),
  FindBugsNullable(ConstraintGroup.ANNO_FINDBUGS, _STANDARD_ANNOTATION, TVL.NO),
  FindBugsPossiblyNull(ConstraintGroup.ANNO_FINDBUGS, _STANDARD_ANNOTATION, TVL.NO),
  FindBugsUnknownNullness(ConstraintGroup.ANNO_FINDBUGS, _STANDARD_ANNOTATION, TVL.NO),
  FindBugsCreatesObligation(ConstraintGroup.ANNO_FINDBUGS, _STANDARD_ANNOTATION,
    TVL.NO), // TODO Jens: needs further
  // discussion, please review
  FindBugsDischargesObligation(ConstraintGroup.ANNO_FINDBUGS, _STANDARD_ANNOTATION,
    TVL.NO), // TODO Jens: needs
  // further discussion,
  // please review
  FindBugsCleanupObligation(ConstraintGroup.ANNO_FINDBUGS, _STANDARD_ANNOTATION,
    TVL.NO), // TODO Jens: needs further
  // discussion, please review

  // Android annotations
  AndroidSuppressLint(ConstraintGroup.ANNO_Android, _STANDARD_ANNOTATION, TVL.NO),
  AndroidTargetApi(ConstraintGroup.ANNO_Android, _STANDARD_ANNOTATION, TVL.NO),


  // AndroidX annotations
  AndroidXAnimatorRes(ConstraintGroup.ANNO_AndroidX, _STANDARD_ANNOTATION, TVL.NO),
  AndroidXAnimRes(ConstraintGroup.ANNO_AndroidX, _STANDARD_ANNOTATION, TVL.NO),
  AndroidXAnyRes(ConstraintGroup.ANNO_AndroidX, _STANDARD_ANNOTATION, TVL.NO),
  AndroidXAnyThread(ConstraintGroup.ANNO_AndroidX, _STANDARD_ANNOTATION, TVL.NO),
  AndroidXArrayRes(ConstraintGroup.ANNO_AndroidX, _STANDARD_ANNOTATION, TVL.NO),
  AndroidXAttrRes(ConstraintGroup.ANNO_AndroidX, _STANDARD_ANNOTATION, TVL.NO),
  AndroidXBinderThread(ConstraintGroup.ANNO_AndroidX, _STANDARD_ANNOTATION, TVL.NO),
  AndroidXBoolRes(ConstraintGroup.ANNO_AndroidX, _STANDARD_ANNOTATION, TVL.NO),
  AndroidXCallSuper(ConstraintGroup.ANNO_AndroidX, _STANDARD_ANNOTATION, TVL.NO),
  AndroidXCheckResult(ConstraintGroup.ANNO_AndroidX, _STANDARD_ANNOTATION, TVL.NO),
  AndroidXChecksSdkIntAtLeast(ConstraintGroup.ANNO_AndroidX, _STANDARD_ANNOTATION, TVL.NO),
  AndroidXColorInt(ConstraintGroup.ANNO_AndroidX, _STANDARD_ANNOTATION, TVL.NO),
  AndroidXColorLong(ConstraintGroup.ANNO_AndroidX, _STANDARD_ANNOTATION, TVL.NO),
  AndroidXColorRes(ConstraintGroup.ANNO_AndroidX, _STANDARD_ANNOTATION, TVL.NO),
  AndroidXContentView(ConstraintGroup.ANNO_AndroidX, _STANDARD_ANNOTATION, TVL.NO),
  AndroidXDimenRes(ConstraintGroup.ANNO_AndroidX, _STANDARD_ANNOTATION, TVL.NO),
  AndroidXDimension(ConstraintGroup.ANNO_AndroidX, _STANDARD_ANNOTATION, TVL.NO),
  AndroidXDoNotInline(ConstraintGroup.ANNO_AndroidX, _STANDARD_ANNOTATION, TVL.NO),
  AndroidXDrawableRes(ConstraintGroup.ANNO_AndroidX, _STANDARD_ANNOTATION, TVL.NO),
  AndroidXFloatRange(ConstraintGroup.ANNO_AndroidX, _STANDARD_ANNOTATION, TVL.NO),
  AndroidXFontRes(ConstraintGroup.ANNO_AndroidX, _STANDARD_ANNOTATION, TVL.NO),
  AndroidXFractionRes(ConstraintGroup.ANNO_AndroidX, _STANDARD_ANNOTATION, TVL.NO),
  AndroidXGuardedBy(ConstraintGroup.ANNO_AndroidX, _STANDARD_ANNOTATION, TVL.NO),
  AndroidXHalfFloat(ConstraintGroup.ANNO_AndroidX, _STANDARD_ANNOTATION, TVL.NO),
  AndroidXIdRes(ConstraintGroup.ANNO_AndroidX, _STANDARD_ANNOTATION, TVL.NO),
  AndroidXInspectableProperty(ConstraintGroup.ANNO_AndroidX, _STANDARD_ANNOTATION, TVL.NO),
  AndroidXIntDef(ConstraintGroup.ANNO_AndroidX, _STANDARD_ANNOTATION, TVL.NO),
  AndroidXIntegerRes(ConstraintGroup.ANNO_AndroidX, _STANDARD_ANNOTATION, TVL.NO),
  AndroidXInterpolatorRes(ConstraintGroup.ANNO_AndroidX, _STANDARD_ANNOTATION, TVL.NO),
  AndroidXIntRange(ConstraintGroup.ANNO_AndroidX, _STANDARD_ANNOTATION, TVL.NO),
  AndroidXKeep(ConstraintGroup.ANNO_AndroidX, _STANDARD_ANNOTATION, TVL.NO),
  AndroidXLayoutRes(ConstraintGroup.ANNO_AndroidX, _STANDARD_ANNOTATION, TVL.NO),
  AndroidXLongDef(ConstraintGroup.ANNO_AndroidX, _STANDARD_ANNOTATION, TVL.NO),
  AndroidXMainThread(ConstraintGroup.ANNO_AndroidX, _STANDARD_ANNOTATION, TVL.NO),
  AndroidXMenuRes(ConstraintGroup.ANNO_AndroidX, _STANDARD_ANNOTATION, TVL.NO),
  AndroidXNavigationRes(ConstraintGroup.ANNO_AndroidX, _STANDARD_ANNOTATION, TVL.NO),
  AndroidXNonNull(ConstraintGroup.ANNO_AndroidX, _STANDARD_ANNOTATION, TVL.NO),
  AndroidXNullable(ConstraintGroup.ANNO_AndroidX, _STANDARD_ANNOTATION, TVL.NO),
  AndroidXPluralsRes(ConstraintGroup.ANNO_AndroidX, _STANDARD_ANNOTATION, TVL.NO),
  AndroidXPx(ConstraintGroup.ANNO_AndroidX, _STANDARD_ANNOTATION, TVL.NO),
  AndroidXRawRes(ConstraintGroup.ANNO_AndroidX, _STANDARD_ANNOTATION, TVL.NO),
  AndroidXRequiresApi(ConstraintGroup.ANNO_AndroidX, _STANDARD_ANNOTATION, TVL.NO),
  AndroidXRequiresFeature(ConstraintGroup.ANNO_AndroidX, _STANDARD_ANNOTATION, TVL.NO),
  AndroidXRequiresPermission(ConstraintGroup.ANNO_AndroidX, _STANDARD_ANNOTATION, TVL.NO),
  AndroidXRestrictTo(ConstraintGroup.ANNO_AndroidX, _STANDARD_ANNOTATION, TVL.NO),
  AndroidXSize(ConstraintGroup.ANNO_AndroidX, _STANDARD_ANNOTATION, TVL.NO),
  AndroidXStringDef(ConstraintGroup.ANNO_AndroidX, _STANDARD_ANNOTATION, TVL.NO),
  AndroidXStringRes(ConstraintGroup.ANNO_AndroidX, _STANDARD_ANNOTATION, TVL.NO),
  AndroidXStyleableRes(ConstraintGroup.ANNO_AndroidX, _STANDARD_ANNOTATION, TVL.NO),
  AndroidXStyleRes(ConstraintGroup.ANNO_AndroidX, _STANDARD_ANNOTATION, TVL.NO),
  AndroidXTransitionRes(ConstraintGroup.ANNO_AndroidX, _STANDARD_ANNOTATION, TVL.NO),
  AndroidXUiThread(ConstraintGroup.ANNO_AndroidX, _STANDARD_ANNOTATION, TVL.NO),
  AndroidXVisibleForTesting(ConstraintGroup.ANNO_AndroidX, _STANDARD_ANNOTATION, TVL.NO),
  AndroidXWorkerThread(ConstraintGroup.ANNO_AndroidX, _STANDARD_ANNOTATION, TVL.NO),
  AndroidXXmlRes(ConstraintGroup.ANNO_AndroidX, _STANDARD_ANNOTATION, TVL.NO),


  // JSR305
  JSR305CheckForNull(ConstraintGroup.ANNO_JSR305, _STANDARD_ANNOTATION, TVL.NO),
  JSR305CheckForSigned(ConstraintGroup.ANNO_JSR305, _STANDARD_ANNOTATION, TVL.NO),
  JSR305MatchesPattern(ConstraintGroup.ANNO_JSR305, _STANDARD_ANNOTATION, TVL.NO),
  JSR305Nonnegative(ConstraintGroup.ANNO_JSR305, _STANDARD_ANNOTATION, TVL.NO),
  JSR305Nonnull(ConstraintGroup.ANNO_JSR305, _STANDARD_ANNOTATION, TVL.NO),
  JSR305Nullable(ConstraintGroup.ANNO_JSR305, _STANDARD_ANNOTATION, TVL.NO),
  JSR305OverridingMethodsMustInvokeSuper(ConstraintGroup.ANNO_JSR305, _POSTCONDITION, TVL.NO),
  JSR305ParametersAreNonnullByDefault(ConstraintGroup.ANNO_JSR305, _PRECONDITION, TVL.NO),
  JSR305ParametersAreNullableByDefault(ConstraintGroup.ANNO_JSR305, _PRECONDITION, TVL.NO),
  JSR305RegEx(ConstraintGroup.ANNO_JSR305, _STANDARD_ANNOTATION, TVL.NO),
  JSR305Signed(ConstraintGroup.ANNO_JSR305, _STANDARD_ANNOTATION, TVL.NO),
  JSR305Syntax(ConstraintGroup.ANNO_JSR305, _STANDARD_ANNOTATION, TVL.NO),
  JSR305Tainted(ConstraintGroup.ANNO_JSR305, _STANDARD_ANNOTATION, TVL.NO),
  JSR305Untainted(ConstraintGroup.ANNO_JSR305, _STANDARD_ANNOTATION, TVL.NO),
  JSR305WillClose(ConstraintGroup.ANNO_JSR305, _STANDARD_ANNOTATION,
    TVL.NO), // TODO Jens: needs further discussion,
  // please review
  JSR305WillCloseWhenClosed(ConstraintGroup.ANNO_JSR305, _STANDARD_ANNOTATION,
    TVL.NO), // TODO Jens: needs further
  // discussion, please review
  JSR305WillNotClose(ConstraintGroup.ANNO_JSR305, _STANDARD_ANNOTATION,
    TVL.NO), // TODO Jens: needs further
  // discussion, please review

  // JSR305 Concurrent
  JSR305CONCURRENTGuardedBy(ConstraintGroup.ANNO_JSR305, _STANDARD_ANNOTATION, TVL.NO),
  JSR305CONCURRENTImmutable(ConstraintGroup.ANNO_JSR305, _STANDARD_ANNOTATION, TVL.NO),
  JSR305CONCURRENTNotThreadSafe(ConstraintGroup.ANNO_JSR305, _STANDARD_ANNOTATION, TVL.NO),
  JSR305CONCURRENTThreadSafe(ConstraintGroup.ANNO_JSR305, _STANDARD_ANNOTATION, TVL.NO),

  // JetBrains and IntelliJ
  JetBrainsContract(ConstraintGroup.ANNO_JetBrains, _UNKNOWN, TVL.MAYBE), // uses DSL
  // skipped NI and NonNIs - only used for code generation / IDE tooling for i18n
  JetBrainsNotNull(ConstraintGroup.ANNO_JetBrains, _STANDARD_ANNOTATION, TVL.NO),
  JetBrainsNullable(ConstraintGroup.ANNO_JetBrains, _STANDARD_ANNOTATION, TVL.NO),
  JetBrainsPropertyKey(ConstraintGroup.ANNO_JetBrains, _PRECONDITION, TVL.NO),
  JetBrainsTestOnly(ConstraintGroup.ANNO_JetBrains, _PRECONDITION, TVL.NO),
  IntellijFlow(ConstraintGroup.ANNO_JetBrains, _PRECONDITION, TVL.NO),
  IntellijIdentifier(ConstraintGroup.ANNO_JetBrains, _STANDARD_ANNOTATION,
    TVL.NO), // TODO Jens: needs further
  // discussion, please review
  IntellijJdkConstants_AdjustableOrientation(ConstraintGroup.ANNO_JetBrains, _STANDARD_ANNOTATION,
    TVL.NO),
  IntellijJdkConstants_BoxLayoutAxis(ConstraintGroup.ANNO_JetBrains, _STANDARD_ANNOTATION, TVL.NO),
  IntellijJdkConstants_CalendarMonth(ConstraintGroup.ANNO_JetBrains, _STANDARD_ANNOTATION, TVL.NO),
  IntellijJdkConstants_CursorType(ConstraintGroup.ANNO_JetBrains, _STANDARD_ANNOTATION, TVL.NO),
  IntellijJdkConstants_FlowLayoutAlignment(ConstraintGroup.ANNO_JetBrains, _STANDARD_ANNOTATION,
    TVL.NO),
  IntellijJdkConstants_FontStyle(ConstraintGroup.ANNO_JetBrains, _STANDARD_ANNOTATION, TVL.NO),
  IntellijJdkConstants_HorizontalAlignment(ConstraintGroup.ANNO_JetBrains, _STANDARD_ANNOTATION,
    TVL.NO),
  IntellijJdkConstants_InputEventMask(ConstraintGroup.ANNO_JetBrains, _STANDARD_ANNOTATION, TVL.NO),
  IntellijJdkConstants_ListSelectionMode(ConstraintGroup.ANNO_JetBrains, _STANDARD_ANNOTATION,
    TVL.NO),
  IntellijJdkConstants_PatternFlags(ConstraintGroup.ANNO_JetBrains, _STANDARD_ANNOTATION, TVL.NO),
  IntellijJdkConstants_TabLayoutPolicy(ConstraintGroup.ANNO_JetBrains, _STANDARD_ANNOTATION,
    TVL.NO),
  IntellijJdkConstants_TabPlacement(ConstraintGroup.ANNO_JetBrains, _STANDARD_ANNOTATION, TVL.NO),
  IntellijJdkConstants_TitledBorderJustification(ConstraintGroup.ANNO_JetBrains,
    _STANDARD_ANNOTATION, TVL.NO),
  IntellijJdkConstants_TitledBorderTitlePosition(ConstraintGroup.ANNO_JetBrains,
    _STANDARD_ANNOTATION, TVL.NO),
  IntellijJdkConstants_Language(ConstraintGroup.ANNO_JetBrains, _STANDARD_ANNOTATION, TVL.NO),
  IntellijJdkConstants_MagicConstant(ConstraintGroup.ANNO_JetBrains, _STANDARD_ANNOTATION, TVL.NO),
  IntellijJdkConstants_Pattern(ConstraintGroup.ANNO_JetBrains, _STANDARD_ANNOTATION, TVL.NO),
  IntellijJdkConstants_PrintFormat(ConstraintGroup.ANNO_JetBrains, _STANDARD_ANNOTATION, TVL.NO),
  IntellijJdkConstants_RegExp(ConstraintGroup.ANNO_JetBrains, _STANDARD_ANNOTATION, TVL.NO),
  IntellijJdkConstants_Subst(ConstraintGroup.ANNO_JetBrains, _STANDARD_ANNOTATION, TVL.NO),

  // Lombok annotations
  Lombok_NonNull(ConstraintGroup.ANNO_Lombok, _STANDARD_ANNOTATION, TVL.NO);
  // other lombok annotations are only used as instructions to generate code

  private ConstraintGroup group = null;
  private Function<ConstraintedArtefact, ConstraintClassification> classifier = null;

  // whether checking a constraint requires a check for all elements of a
  // collection
  // or array, including checks on all characters of a string
  private TVL isQuantifying = TVL.MAYBE;

  ConstraintType(ConstraintGroup group,
    Function<ConstraintedArtefact, ConstraintClassification> classifier) {
    this.group = group;
    this.classifier = classifier;
  }

  ConstraintType(ConstraintGroup group,
    Function<ConstraintedArtefact, ConstraintClassification> classifier,
    TVL isQuantifying) {
    this.group = group;
    this.classifier = classifier;
    this.isQuantifying = isQuantifying;
  }

  public ConstraintGroup getGroup() {
    return group;
  }

  public ConstraintClassification getClassification(ConstraintedArtefact artefact) {
    return classifier.apply(artefact);
  }

  public TVL isQuantifying() {
    return isQuantifying;
  }

}
